### ISSUE TITLE
Can no longer compile doconce file in another folder

### ISSUE THREAD

**Issue by lexnederbragt** [doconce/doconce#114]
I recently updated DocOnce to the latest commit (ea41df34) and encountered a problem. I did a ‘git bisect’ and it seems that https://github.com/doconce/doconce/commit/8b2db74a352d3a9d91133b6db0fd8688c8b5550a was the commit that caused this.

To replicate:

```
git clone https://github.com/lexnederbragt/doconce_demo
cd doconce_demo
doconce format html text1/text1.do.txt
```

Output:

```
Traceback (most recent call last):
  File "/anaconda3/envs/doconce_delete_me/bin/doconce", line 223, in <module>
    bg_session = main()
  File "/anaconda3/envs/doconce_delete_me/bin/doconce", line 213, in main
    retval = eval(command + '()')
  File "<string>", line 1, in <module>
  File "/anaconda3/envs/doconce_delete_me/bin/doconce", line 177, in format
    bg_session = doconce.doconce.format_driver()
  File "/anaconda3/envs/doconce_delete_me/lib/python3.9/site-packages/doconce/doconce.py", line 5369, in format_driver
    filename_preprocessed = preprocess(globals.filename, format, preprocessor_options)
  File "/anaconda3/envs/doconce_delete_me/lib/python3.9/site-packages/doconce/doconce.py", line 4872, in preprocess
    f = open(filename_in, 'r'); filestr = f.read(); f.close()
FileNotFoundError: [Errno 2] No such file or directory: 'text1.do.txt'
```

When I do this, it works:

```
cd text1
doconce format html text1.do.txt
```

So there seems to be a problem when doconce is asked to compile a file in another folder.

**Comment by lexnederbragt** [comment]
Thanks, problem solved!
